### PR TITLE
 Don't serve a cached page when a request with an active session comes in

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by christoph-kluge** [comment]
Hi @WyriHaximus, wouldn't it be more feasible to add an extension to the cache middleware rather then depending on some session module? This feels to me like a strict vendor lock-in here.

**Comment by WyriHaximus** [comment]
Hey @christoph-kluge I'm open to ideas and suggestions. Initially wrote this to see how viable it is (which is why I did a vendor lock in) before continuing. Another path could be to check if a certain attribute is present, or to provide a callable that does the checking and returns a `true` or `false`.

**Comment by christoph-kluge** [comment]
Just out of my head I would add an ConfigurationInterface either `__construct(CacheConfigurationInterface $conf, CacheInterface $cache = null)` and then use something like `$conf->isCachable($request)` inside the Middleware? It will break BC but I think it still looks nice and is pretty intuitive for customization. 

```
$server = new Server([
    /** Other middleware */
    new ResponseCacheMiddleware(
        new CacheConfiguration([
            '/',
            '/robots.txt',
            '/favicon.ico',
            '/cache/***', // Anything that starts with /cache/ in the path will be cached
            '/api/???', // Anything that starts with /cache/ in the path will be cached (query is included in the cache key)
            ],
            [ // Optional, array with headers to include in the cache
                'Content-Type',
            ]
        ),
        new ArrayCache()
    ),
    /** Other middleware */
]);
```

One of my clients does also cache session-based/per-customer-based responses with an high cache-ratio. 

What do you feel about it?

**Comment by WyriHaximus** [comment]
Sounds good, it's going to be a BC break so `2.0` will have to be tagged but liking the idea. This also removes the responsibility out of the middleware 👍

**Comment by kelunik** [comment]
You can also examine the cache-control header, which should be set to private in case there's an active session by the session middleware. The downside is that the user has to remember that to right order of both middleware instances.

**Comment by WyriHaximus** [comment]
> You can also examine the cache-control header, which should be set to private in case there's an active session by the session middleware.

I'll add support for that as well but rather support both to be sure.

> The downside is that the user has to remember that to right order of both middleware instances.

Yup that is going to be an issue to be solved with documentation.

**Comment by WyriHaximus** [comment]
@christoph-kluge I'll start working on that change you suggested now

**Comment by WyriHaximus** [comment]
@christoph-kluge the PR for your suggestion is up at: https://github.com/WyriHaximus/reactphp-http-middleware-response-cache/pull/4

**Pull request merged**
